version: "3.8"
services:
  posgresDB:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_crud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
volumes:
  postgres_data: